### PR TITLE
New version: Literate v2.0.6

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
I had a typo in the `.travis.yml` file.

**Comment by DilumAluthge** [comment]
Automerge looked at the `master` branch and saw that the most recent version of Literate was `2.0.4`. Then it looked at this PR and saw that the version here is `2.0.4`. Since your version number didn't change, automerge does not want to automerge it.

**Comment by DilumAluthge** [comment]
@fredrikekre 

> I was not able to install and import the package. See the Travis logs for details. 

Everything working correctly :) Since this PR changed the URL to a broken URL.

**Comment by fredrikekre** [comment]
I just wanna hack it!

**Comment by fredrikekre** [comment]
So this should not be green I think...

**Comment by fredrikekre** [comment]
So we should check the following for a new version PR:
1. Files for other packages should not be allowed to change
2. Package.toml should not be allowed to change for the package (`Literate/Package.toml` in this case)

**Comment by DilumAluthge** [comment]
(haven't gone to sleep just yet)

If a pull request is made by @JuliaRegistrator, we are guaranteed that 1, 2, and 3 above are met. (Since we have control over how @JuliaRegistrator makes PRs.)

So that's why I only consider PRs made by @JuliaRegistrator.

**Comment by DilumAluthge** [comment]
https://github.com/JuliaRegistries/General/issues/3673#issuecomment-516040723

**Comment by DilumAluthge** [comment]
This does mean that we place trust that JuliaRegistrator is making honest PR's. But we control that account, and PRs by that account are only made using Registrator.jl, and we control Registrator.jl, so I feel comfortable trusting PRs from JuliaRegistrator.

**Comment by DilumAluthge** [comment]
@fredrikekre I gave this some more thought, and you are right. In the automerge code, we should check those 3 things. I’ll add that functionality when I am able to, hopefully either this weekend or next week.

**Comment by fredrikekre** [comment]
Unless it is too difficult I think it makes sense to verify as much as possible.

**Comment by DilumAluthge** [comment]
> Unless it is too difficult I think it makes sense to verify as much as possible.

I think that you are right.

It will be feasible to add the following checks:

For new packages, they are only allowed to modify the following files:
- `Registry.toml`
- `F/Foo/Compat.toml`
- `F/Foo/Deps.toml`
- `F/Foo/Package.toml`
- `F/Foo/Version.toml`


For new versions of existing packages, they are only allowed to modify the following files:
- `F/Foo/Compat.toml`
- `F/Foo/Deps.toml`
- `F/Foo/Version.toml`

@fredrikekre Are there any other checks that you think we need to add?

**Comment by fredrikekre** [comment]
> @fredrikekre Are there any other checks that you think we need to add?

No, lets add these and then get the automerger merged!

Btw, should we move the automerge code to the separate repo?

**Comment by DilumAluthge** [comment]
Sounds good. I'm recovering from a mild illness right now, so I won't be able to make those changes immediately, but hopefully I'll be able to get to it either this weekend or next week.

Once I've made the changes, I'll open a new pull request to https://github.com/JuliaRegistries/GeneralRegistryCI.jl

**Pull request merged**
